# Generated by Django 2.1.5 on 2019-01-23 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('friend1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Friend1', to='core.Person')),
                ('friend2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Friend2', to='core.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('person1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Person1', to='core.Person')),
                ('person2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Person2', to='core.Person')),
            ],
        ),
    ]
